logging:
  pattern:
    console: "[API Gateway] %clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  
server:
  port: 9991
  
spring:
  application:
    name: api-gateway
  main:
    banner-mode: OFF
  devtools:
    restart:
      additional-paths:
      - conf/**
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
        health-check-path: /ping
        instance-id: api-gateway-${random.int}
  sleuth:
    sampler:
      probability: 1.0
