logging:
  pattern:
    console: "[Eshop Payment] %clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  
server:
  port: 8890
  
spring:
  application:
    name: eshop-payment
  main:
    banner-mode: OFF
  jackson:
    default-property-inclusion: non-null