logging:
  pattern:
    dateformat: "HH:mm:ss.SSS"
  file:
    name: log/microservice-chassis.log
  
spring:
  application:
    name: microservice-chassis
  main:
    banner-mode: OFF
  devtools:
    restart:
      additional-paths:
      - conf/**
        
server:
  port: 8004